[package]
name = "lightningparse"
version = "0.4.1"
edition = "2021"

[lib]
name = "lightningparse"
crate-type = ["cdylib", "rlib"]

[dependencies]
image = "0.24"
lopdf = "0.44"
pyo3 = { version = "0.21", features = ["extension-module"] }
rayon = "1.10"
rusty-tesseract = "1.1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.27.0"
thiserror = "1.0"
