import os
import json
import pytest
import lightningparse

def test_corrupt_pdf_raises_exception(tmp_path):
    """
    Negative path: parsing random garbage bytes should raise a CorruptPdfError,
    proving that our Rust error handling maps correctly across the FFI boundary
    instead of crashing the Python process.
    """
    garbage_file = tmp_path / "garbage.pdf"
    garbage_file.write_bytes(os.urandom(1024))
    
    with pytest.raises(lightningparse.CorruptPdfError):
        lightningparse.parse_pdf(str(garbage_file))


def test_fault_tolerant_page_tree_extraction(tmp_path):
    """
    Positive path: parsing a genuinely malformed PDF (e.g. missing /Type /Pages)
    should succeed via our tolerant walker, returning real extracted text.
    """
    # Load a known valid PDF from the benchmark corpus
    corpus_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "benchmarks", "corpus")
    original_pdf_path = os.path.join(corpus_dir, "digital_word_export.pdf")
    
    with open(original_pdf_path, "rb") as f:
        pdf_bytes = f.read()
        
    # Introduce a mutation that breaks lopdf's strict page enumeration.
    # We replace b"/Type /Pages" with b"/Type /PaXes".
    # This keeps the exact same byte length, preserving xref table offsets,
    # but makes it fail the strict /Type check.
    assert b"/Type /Pages" in pdf_bytes or b"/Type/Pages" in pdf_bytes or b"/Pages" in pdf_bytes, "Expected to find Pages dictionary in fixture"
    
    # We'll just target the string directly. PDFs might format it differently, 
    # so we'll try a few variations.
    mutated_bytes = pdf_bytes.replace(b"/Type /Pages", b"/Type /PaXes")
    mutated_bytes = mutated_bytes.replace(b"/Type/Pages", b"/Type/PaXes")
    
    # If the bytes didn't change, we might need a more robust replacement for this specific fixture,
    # but digital_word_export.pdf (generated by fpdf) uses explicit /Type /Pages.
    assert mutated_bytes != pdf_bytes, "Failed to mutate the PDF; could not find /Type /Pages pattern."
    
    malformed_file = tmp_path / "malformed.pdf"
    malformed_file.write_bytes(mutated_bytes)
    
    # Parse the malformed PDF
    result_json_str = lightningparse.parse_pdf(str(malformed_file))
    result = json.loads(result_json_str)
    
    # Verify that we actually extracted pages and text
    assert len(result["pages"]) > 0
    assert result["metadata"]["page_count"] == len(result["pages"])
    
    # Verify real text was extracted
    first_page = result["pages"][0]
    assert len(first_page["blocks"]) > 0
    assert len(first_page["blocks"][0]["text"]) > 0
